from typing import List, Optional, Annotated

from pydantic import Field

from app.structures.agents.base_rainbow_agent_state import BaseRainbowAgentState
from app.structures.artifacts.pulsar_palace_encounter_artifact import (
    PulsarPalaceEncounterArtifact,
)
from app.structures.concepts.pulsar_palace_character import PulsarPalaceCharacter
from app.structures.concepts.pulsar_palace_room import PulsarPalaceRoom


class YellowAgentState(BaseRainbowAgentState):

    characters: Annotated[List[PulsarPalaceCharacter], lambda x, y: y if y else x] = (
        Field(
            default_factory=list,
            max_length=4,
            description="The Pulsar Palace RPG-style characters for a given game run.",
        )
    )
    rooms: Annotated[List[PulsarPalaceRoom], lambda x, y: y if y else x] = Field(
        default_factory=list,
        description="Room from the Pulsar Palace RPG-style game run available in the current run.",
    )
    encounter_narrative_artifact: Annotated[
        Optional[PulsarPalaceEncounterArtifact], lambda x, y: y or x
    ] = Field(
        default=None,
        description="Narrative artifact generated by the encounter generator.",
    )
    story_elaboration_level: Annotated[int, lambda x, y: y if y is not None else x] = (
        Field(
            default=0,
            description="Number of times the story has been elaborated on. To prevent infinite looping",
            lt=4,
        )
    )
    current_room_index: Annotated[int, lambda x, y: y if y is not None else x] = Field(
        default=0, description="Index of the current room in the story"
    )
    should_add_to_story: Annotated[bool, lambda x, y: y if y is not None else x] = (
        Field(
            default=False,
            description="Whether the current run should be added to the game run",
        )
    )
    max_rooms: Annotated[Optional[int], lambda x, y: y or x] = Field(
        default=None, description="Maximum number of rooms"
    )

    def __init__(self, **data):
        # Rebuild model to resolve forward references if needed
        if not hasattr(self.__class__, "_rebuilt"):
            # Import at runtime to ensure all forward references are resolved
            from app.structures.artifacts.pulsar_palace_character_sheet import (
                PulsarPalaceCharacterSheet as _PulsarPalaceCharacterSheet,
            )
            from app.structures.concepts.pulsar_palace_character import (
                PulsarPalaceCharacter as _PulsarPalaceCharacter,
            )

            self.__class__.model_rebuild(
                _types_namespace={
                    "PulsarPalaceCharacter": _PulsarPalaceCharacter,
                    "PulsarPalaceCharacterSheet": _PulsarPalaceCharacterSheet,
                }
            )
            self.__class__._rebuilt = True
        super().__init__(**data)
