from typing import List, Optional

from pydantic import Field

from app.structures.agents.base_rainbow_agent_state import BaseRainbowAgentState
from app.structures.artifacts.pulsar_palace_encounter_artifact import (
    PulsarPalaceEncounterArtifact,
)
from app.structures.concepts.pulsar_palace_character import PulsarPalaceCharacter
from app.structures.concepts.pulsar_palace_room import PulsarPalaceRoom


class YellowAgentState(BaseRainbowAgentState):

    characters: List[PulsarPalaceCharacter] = Field(
        default_factory=list,
        max_length=4,
        description="The Pulsar Palace RPG-style characters for a given game run.",
    )
    rooms: List[PulsarPalaceRoom] = Field(
        default_factory=list,
        description="Room from the Pulsar Palace RPG-style game run available in the current run.",
    )
    encounter_narrative_artifact: Optional[PulsarPalaceEncounterArtifact] = Field(
        default=None,
        description="Narrative artifact generated by the encounter generator.",
    )
    story_elaboration_level: int = Field(
        default=0,
        description="Number of times the story has been elaborated on. To prevent infinite looping",
        lt=4,
    )
    current_room_index: int = Field(
        default=0, description="Index of the current room in the story"
    )
    should_add_to_story: bool = Field(
        default=False,
        description="Whether the current run should be added to the game run",
    )
    max_rooms: Optional[int] = Field(
        default=None, description="Maximum number of rooms"
    )

    def __init__(self, **data):
        super().__init__(**data)
