CAUSAL_WORDS = [
    # Core causality
    "because",
    "caused",
    "cause",
    "result",
    "resulted",
    "resulting",
    "consequence",
    "consequently",
    "therefore",
    "thus",
    "hence",
    "so",
    # Reason and explanation
    "reason",
    "why",
    "explanation",
    "explain",
    "due to",
    "owing to",
    "on account of",
    "thanks to",
    "attributed to",
    "stemmed from",
    # Effect and impact
    "effect",
    "affected",
    "impact",
    "impacted",
    "influenced",
    "influence",
    "outcome",
    "upshot",
    "ramification",
    "repercussion",
    "fallout",
    # Physical injury/harm
    "injury",
    "injured",
    "hurt",
    "hurting",
    "pain",
    "painful",
    "wound",
    "wounded",
    "damage",
    "damaged",
    "harm",
    "harmed",
    "trauma",
    "traumatic",
    "bruise",
    "bruised",
    "cut",
    "laceration",
    # Accidents and incidents
    "accident",
    "accidental",
    "incident",
    "mishap",
    "collision",
    "crash",
    "fall",
    "fell",
    "fallen",
    "drop",
    "dropped",
    "slip",
    "slipped",
    "trip",
    "tripped",
    "stumble",
    "stumbled",
    # Breaking and rupture
    "broke",
    "broken",
    "break",
    "breaking",
    "fracture",
    "fractured",
    "shatter",
    "shattered",
    "crack",
    "cracked",
    "split",
    "tear",
    "torn",
    "rip",
    "ripped",
    "rupture",
    "ruptured",
    "snap",
    "snapped",
    # Action and reaction
    "led to",
    "leads to",
    "leading to",
    "brought about",
    "resulted in",
    "gave rise to",
    "triggered",
    "trigger",
    "prompted",
    "provoked",
    "induced",
    "generated",
    "produced",
    "created",
    "made",
    # Chain of events
    "then",
    "after",
    "afterward",
    "following",
    "subsequently",
    "next",
    "sequence",
    "chain",
    "series",
    "cascade",
    # Conditions and prerequisites
    "if",
    "when",
    "whenever",
    "condition",
    "conditional",
    "prerequisite",
    "necessary",
    "required",
    "needed",
    "depends",
    "dependent",
    # Blame and responsibility
    "fault",
    "blame",
    "responsible",
    "responsibility",
    "culpable",
    "accountable",
    "liable",
    "guilty",
    "caused by",
    "fault of",
    # Force and compulsion
    "force",
    "forced",
    "compel",
    "compelled",
    "made to",
    "had to",
    "driven",
    "pushed",
    "pressured",
    "coerced",
    # Prevention and enablement
    "prevent",
    "prevented",
    "stop",
    "stopped",
    "block",
    "blocked",
    "enable",
    "enabled",
    "allow",
    "allowed",
    "permit",
    "permitted",
]
