SPATIAL_WORDS = [
    # Vertical positions
    "above",
    "below",
    "over",
    "under",
    "beneath",
    "underneath",
    "top",
    "bottom",
    "up",
    "down",
    "upward",
    "downward",
    "overhead",
    "underfoot",
    "high",
    "low",
    "higher",
    "lower",
    "upper",
    "lower",
    "elevated",
    "sunken",
    # Horizontal positions
    "left",
    "right",
    "side",
    "beside",
    "next to",
    "adjacent",
    "alongside",
    "parallel",
    "perpendicular",
    "lateral",
    "horizontal",
    "vertical",
    # Directional words
    "north",
    "south",
    "east",
    "west",
    "northeast",
    "northwest",
    "southeast",
    "southwest",
    "forward",
    "backward",
    "ahead",
    "behind",
    "front",
    "back",
    "rear",
    "fore",
    "backwards",
    "forwards",
    "onward",
    "reverse",
    # Distance and proximity
    "near",
    "far",
    "close",
    "distant",
    "nearby",
    "remote",
    "proximate",
    "adjacent",
    "neighboring",
    "immediate",
    "faraway",
    "close by",
    "distance",
    "proximity",
    "reach",
    "within",
    "beyond",
    "outside",
    # Location and placement
    "location",
    "locate",
    "located",
    "place",
    "placed",
    "placement",
    "position",
    "positioned",
    "positioning",
    "site",
    "situated",
    "situation",
    "spot",
    "point",
    "area",
    "region",
    "zone",
    "sector",
    "locale",
    # Interior and exterior
    "inside",
    "outside",
    "interior",
    "exterior",
    "inner",
    "outer",
    "within",
    "without",
    "internal",
    "external",
    "indoors",
    "outdoors",
    "enclosed",
    "open",
    "contained",
    "surrounding",
    # Spatial questions
    "where",
    "whereabouts",
    "which place",
    "what place",
    "whither",
    "whence",
    # Demonstratives
    "here",
    "there",
    "yonder",
    "this place",
    "that place",
    "these places",
    "those places",
    "everywhere",
    "somewhere",
    "nowhere",
    "anywhere",
    # Between and among
    "between",
    "among",
    "amongst",
    "amid",
    "amidst",
    "middle",
    "center",
    "central",
    "centered",
    "midpoint",
    "halfway",
    "intermediate",
    # Surrounding and enclosing
    "around",
    "surrounding",
    "encircling",
    "encompassing",
    "enclosed",
    "contained",
    "bounded",
    "circumference",
    "perimeter",
    "boundary",
    # Movement through space
    "across",
    "through",
    "throughout",
    "along",
    "past",
    "by",
    "via",
    "toward",
    "towards",
    "away",
    "from",
    "to",
    "into",
    "onto",
    "off",
    # Arrangement and order
    "arrangement",
    "arranged",
    "order",
    "ordered",
    "organized",
    "layout",
    "configuration",
    "alignment",
    "aligned",
    "distributed",
    "scattered",
    "clustered",
    "grouped",
    "separated",
    "dispersed",
    # Orientation
    "facing",
    "oriented",
    "orientation",
    "direction",
    "pointed",
    "aimed",
    "angled",
    "tilted",
    "rotated",
    "turned",
    "aligned",
    "diagonal",
    # Dimensional space
    "space",
    "spatial",
    "dimension",
    "dimensional",
    "area",
    "volume",
    "expanse",
    "extent",
    "span",
    "breadth",
    "width",
    "length",
    "height",
    "depth",
    "radius",
    "diameter",
    "circumference",
    # Topographical
    "landscape",
    "terrain",
    "topography",
    "geography",
    "map",
    "mapped",
    "coordinate",
    "coordinates",
    "grid",
    "axis",
    "plane",
    "surface",
]
