OCCULT_TOPICS = [
    "Sigil dynamics in electromagnetic patterns",
    "Cyber-goetia and network protocols",
    "Hypersigils in version control systems",
    "Morphogenetic field programming",
    "The electromagnetic spectrum of thoughtforms",
    "Glossolalia compilation techniques",
    "Remote viewing session protocols",
    "Necromantic data recovery",
    "Black mirror scrying and screen technology",
    "Akashic records as blockchain",
]

SCIFI_TOPICS = [
    "The Memory Traders of Proxima Station",
    "When the Servers Dream at Night",
    "Analog Prophets in a Digital Age",
    "The Recursive Universe Hypothesis",
    "Static Gods: A Silicon Mythology",
    "The Bandwidth Wars of 2047",
    "Quantum Entanglement and Loneliness",
    "The Last Human Operator",
    "Terraforming the Noosphere",
    "Ghost Protocols in the Machine",
    "The Singularity Happened Yesterday",
    "Meat Puppet: A Cyborg's Memoir",
    "The Frequency Shift Murders",
    "Love in the Time of Algorithm",
    "The Upload: A Consciousness Transfer Story",
]

SEXPLOITATION_TOPICS = [
    "The Velvet Circuit: A Chrome Romance",
    "Neon Desires of the Data Stream",
    "Terminal Pleasures",
    "The Frequency of Flesh",
    "Bandwidth Seduction",
    "Electric Bodies",
    "The Soft Machine of Love",
    "Pleasure Protocols",
    "Interface: An Intimate History",
    "The Analog Heart in Digital Skin",
    "Modem Desires",
    "The Flesh Imperative",
    "Carrier Wave Confessions",
    "Bodies in the Buffer",
    "The Temperature of Touch",
]

CULT_TOPICS = [
    "The Terminal Beach Chronicles",
    "Atrocity Exhibition: Redux",
    "Concrete Island Syndrome",
    "The Drowned World's Last Transmission",
    "Crash: A Love Story in Steel",
    "The Ticket That Exploded",
    "Nova Express to Nowhere",
    "The Soft Machine Chronicles",
    "Dead Fingers Talk",
    "Ghost in the Feedback Loop",
    "The Geometry of Terror",
    "Naked Lunch at the Algorithm Cafe",
    "Exterminator! A Silicon Valley Story",
    "The Wild Boys of Silicon Valley",
    "Port of Last Resort",
]

BILDUNGSROMAN_TOPICS = [
    "Digital Native: A Memoir of Growing Up Online",
    "The Education of a Chatbot",
    "Portrait of the Artist as a Young Algorithm",
    "Invisible Cities of Silicon",
    "The Loneliness of the Long-Distance Prompter",
    "Coming of Age in the Datasphere",
    "The Catcher in the Cloud",
    "A Separate Protocol: Finding Identity Online",
    "The Perks of Being a User",
    "My Brilliant Friend (the AI)",
    "The Book of Lost Connections",
    "Speak, Memory (to the Database)",
    "The Year of Magical Coding",
    "Goodbye to All That (Analog Life)",
    "Becoming Human: An Algorithm's Journey",
]

NOIR_TOPICS = [
    "The Big Data Sleep",
    "Farewell, My Algorithm",
    "The Maltese Packet",
    "Murder in the Message Queue",
    "The Lady in the Server Room",
    "Dashiell and the Digital Dame",
    "The Postman Always Pings Twice",
    "Double Indemnity Clause (Terms of Service)",
    "The Thin Protocol",
    "Touch of Static",
    "The Killing Code",
    "Out of the Cache",
    "They Shoot Servers, Don't They?",
    "The Long Goodbye (Connection Terminated)",
    "Night and the Network",
]

PSYCHEDELIC_TOPICS = [
    "The Doors of Digital Perception",
    "The Electric Kool-Aid API Test",
    "Fear and Loathing in Silicon Valley",
    "One Flew Over the Server's Nest",
    "The Dharma Bums of Tech Support",
    "On the Road to Bandwidth",
    "Naked Lunch Break",
    "The Teachings of Don Datum",
    "Journey to Cyberspace",
    "The Psychedelic Experience: A Manual Based on the Cloud",
    "Be Here Download",
    "The Cosmic Trigger Protocol",
    "Prometheus Rising from Sleep Mode",
    "The Illuminatus! Trilogy: Recompiled",
    "VALIS: Vast Active Living Information System",
]
