MUSIC_PUBLICATIONS = [
    "The Quietus",
    "Stereogum",
    "Gorilla vs. Bear",
    "Brooklyn Vegan",
    "Consequence",
    "Paste Magazine",
    "Under the Radar",
    "The Line of Best Fit",
    "DIY Magazine",
    "NME",
    "The FADER",
    "Tiny Mix Tapes",
    "Drowned in Sound",
    "Exclaim!",
    "Treble Zine",
    "PopMatters",
    "The Needle Drop",
    "Uproxx",
    "The A.V. Club",
    "Spin",
    "Mojo",
    "Uncut",
    "Q Magazine",
    "Wire",
    "The Wire",
    "Magnet",
    "Dusted Magazine",
    "Stylus Magazine",
    "Cokemachineglow",
    "Prefix Magazine",
    "Impose Magazine",
    "Beats Per Minute",
    "AllMusic",
    "Resident Advisor",
    "XLR8R",
    "Fact Magazine",
    "Loud and Quiet",
    "So Young Magazine",
    "The Indiependent",
    "Clash Magazine",
]

# Defunct/nostalgia publications (for Vanity Pressing Fan persona)
NOSTALGIC_PUBLICATIONS = [
    "Dusted Magazine",
    "Stylus Magazine",
    "Cokemachineglow",
    "Prefix Magazine",
    "Impose Magazine",
    "Drowned in Sound",
    "Tiny Mix Tapes",
    "Filter Magazine",
    "Venus Zine",
    "Plan B Magazine",
    "The Big Takeover",
    "Alternative Press",
    "Magnet Magazine",
]

# Pretentious/academic publications (for Experimental Purist persona)
EXPERIMENTAL_PUBLICATIONS = [
    "The Wire",
    "Sound American",
    "eContact!",
    "Computer Music Journal",
    "Organised Sound",
    "Leonardo Music Journal",
    "Tempo",
    "Contemporary Music Review",
    "Perspectives of New Music",
    "Experimental Music Yearbook",
    "Noise & Notes",
    "Neural Magazine",
    "Musique Machine",
    "Perfect Sound Forever",
]

# Online/blog publications (for Earnest Misreader persona)
BLOG_PUBLICATIONS = [
    "Gorilla vs. Bear",
    "Said the Gramophone",
    "Stereogum",
    "Brooklyn Vegan",
    "Aquarium Drunkard",
    "Music for Robots",
    "I Guess I'm Floating",
    "20 Jazz Funk Greats",
    "Weird Canada",
    "Imposed Magazine",
    "Chocolate Bobka",
    "Mystic Chords & Sacred Spaces",
    "Lost in the Manor",
    "The Blue Walrus",
]
