id: graham-hopkins
name: Graham Hopkins
roles:
- drummer
email: grahamhopkinsdrummer@gmail.com
photo_url: https://lh5.googleusercontent.com/proxy/sP32xT-hMZpkFXTc3_djWpDgTyR_7wDYBMuxC9iDD_-7_0vbkwJutO4SWcT_V6RxY0J1AnbEN82aodVQRXOdQb43PzZl9OXtQFXnW9kC5BeJ
platforms:
- platform: airgigs
  url: https://www.airgigs.com/user/grahamhopkinsdrummer
  username: grahamhopkinsdrummer
website: https://grahamhopkinsdrummer.com/
socials:
  ? ''
  : https://www.instagram.com/graham_hopkins/
pro_affiliation: none
pro_number: null
availability_windows: []
notes: ''
