ACQUISITION_NOTES = [
    "Found in estate sale, previous owner unknown",
    "Traded for at underground book fair",
    "Recovered from abandoned university library",
    "Anonymous package, no return address",
    "Purchased from seller who seemed nervous",
    "Found in condemned building",
    "Inherited from disappeared colleague",
    "Confiscated copy, released to public domain",
    "Photocopied from library before fire",
    "Acquired at auction, provenance unclear",
    "Gift from anonymous benefactor",
    "Smuggled out of restricted archive",
    "Discovered in used bookstore back room",
    "Salvaged from defunct publisher's warehouse",
    "Mail-order from obscure catalog, 1970s",
]

SUPPRESSION_STORIES = [
    "Banned by university ethics board in 1973",
    "Publisher ceased operations under mysterious circumstances",
    "Author disappeared before publication",
    "Recalled shortly after release, reason undisclosed",
    "Subject of government investigation",
    "Denounced by multiple professional societies",
    "Library copies systematically destroyed",
    "Publisher served with cease and desist",
    "Author recanted findings under pressure",
    "Classified upon discovery of implications",
    "Obscenity charges led to pulping of first edition",
    "Seized by customs, banned from import",
    "Author sued for libel, book withdrawn",
    "Too controversial for mainstream distribution",
]
