NEGATIVE_ARTISTS: list[str] = [
    "Devendra Banhart",
    "Grizzly Bear",
    "The Microphones",
    "The Mountain Goats",
    "Whitney Houston",
    "Mariah Carey",
    "Celine Dion",
    "Justin Timberlake",
    "Britney Spears",
    "Backstreet Boys",
    "NSYNC",
    "Spice Girls",
    "Anthrax",
    "Metallica",
    "Megadeth",
    "Slayer",
    "Pantera",
    "Iron Maiden",
    "Judas Priest",
    "AC/DC",
    "Van Morrison",
    "Joni Mitchell",
    "Arlo Guthrie",
    "King Crimson",
    "The Allman Brothers Band",
    "The Doobie Brothers",
    "Peter, Paul and Mary",
    "Simon & Garfunkel",
    "The White Stripes",
    "The Pixies",
    "The Police",
    "Traveling Wilburys",
    "The Beach Boys",
    "Pink Floyd",
    "Morrissey",
    "Moby",
    "Aphex Twin",
    "Grimes",
    "FKA twigs",
    "Justin Bieber",
    "Nickelback",
    "Creed",
    "Maroon 5",
    "Imagine Dragons",
    "Coldplay",
    "Katy Perry",
    "Ed Sheeran",
    "Pitbull",
    "Black Eyed Peas",
    "One Direction",
    "Drake",
    "Kanye West",
    "Travis Scott",
    "Future",
    "Lil Uzi Vert",
    "Cardi B",
    "Nicki Minaj",
    "Migos",
    "Snoop Dogg",
    "50 Cent",
    "Flo Rida",
    "Pitbull",
    "W.A.S.P.",
    "Guns N' Roses",
    "Def Leppard",
    "Bon Jovi",
    "Aerosmith",
    "Van Halen",
    "Poison",
    "Motley Crue",
    "Scorpions",
    "Twisted Sister",
    "Europe",
    "Journey",
    "Foreigner",
    "REO Speedwagon",
    "Kansas",
    "Styx",
    "Boston",
    "Cheap Trick",
    "Toto",
    "Asia",
    "Survivor",
    "Warrant",
    "Cinderella",
    "Skid Row",
    "Winger",
    "Tesla",
    "Great White",
    "Slaughter",
    "LA Guns",
    "BulletBoys",
    "The Strokes",
    "Arctic Monkeys",
    "Tame Impala",
    "Fleet Foxes",
    "Bon Iver",
    "Sufjan Stevens",
    "Iron & Wine",
    "Death Cab for Cutie",
    "The Decemberists",
    "Mumford & Sons",
]
