NEGATIVE_GENRES: list[str] = [
    "Blues Rock",
    "Polka",
    "Vandeville",
    "Anti-Folk",
    "Grunge",
    "Gospel Blues",
    "Contemporary R&B",
    "Progressive Rock"
    "Canadian Blues",
    "Punk Blues",
    "Zydeco",
    "Wedding Music",
    "Novelty",
    "Comedy",
    "Reactionary Bluegrass",
    "Country Gospel",
    "Bluegrass Gospel",
    "Exercise",
    "Hi-NRG",
    "Acid House",
    "Background",
    "Lounge",
    "Chiptune",
    "Crunk",
    "Jazz Rap",
    "Latin Rap",
    "Gangsta Rap",
    "Holiday",
    "Christian Rap",
    "Christian Rock",
    "Christian Metal",
    "Christian Punk",
    "Christian Pop",
    "Christian Contemporary",
    "Christian Country",
    "Christian Hip Hop",
    "Christian Electronic",
    "Christian Indie",
    "Christian Alternative",
    "Christian Worship",
    "Marching Band",
    "Military",
    "Dixieland",
    "K-Pop",
    "Hair Metal",
    "New Age Healing",
    "Pop Punk",
    "Ska",
    "Adult-Oriented Rock",
    "Contemporary Folk",
    "Spoken Word",
]