NEGATIVE_SOUNDS_LIKE_LOCATIONS: list[str] = [
    "at Coachella",
    "at Glastonbury",
    "at Lollapalooza 2023",
    "in a mall",
    "at a corporate event",
    "at a wedding",
    "at an amusement park",
    "at a high school talent show",
    "at a poorly attended concert",
    "at a $500-dollar-a-seat stadium concert",
    "up your mom's ass",
    "in a children's cancer ward",
    "in a Starbucks",
    "in a dentist's office",
    "in a fast food restaurant",
    "in a grocery store",
    "in a hospital waiting room",
]