POSITIVE_ARTISTS: list[str] = [
    "Stereolab",
    "The Beatles",
    "David Bowie",
    "The Velvet Underground",
    "Syd Barrett",
    "Brian Wilson",
    "The Smiths",
    "The Cure",
    "Joy Division",
    "Radiohead",
    "Sigur Rós",
    "Mogwai",
    "Godspeed You! Black Emperor",
    "Beach House",
    "James Blake",
    "Boards of Canada",
    "Burial",
    "Flying Lotus",
    "Ólafur Arnalds",
    "Max Richter",
    "Philip Glass",
    "Steve Reich",
    "Arvo Pärt",
    "John Adams",
    "Gustavo Santaolalla",
    "Hildur Guðnadóttir",
    "Ludovico Einaudi",
    "Taylor Swift",
    "Beyoncé",
    "Billie Eilish",
    "Creedence Clearwater Revival",
    "The Ramones",
    "The Clash",
    "Sonic Youth",
    "Neutral Milk Hotel",
    "Olivia Tremor Control",
    "Pavement",
    "Sebadoh",
    "The Flaming Lips",
    "Wilco",
    "Fleetwood Mac",
    "Scott Walker",
    "Kate Bush",
    "Nick Drake",
    "Hood",
    "His Name Is Alive",
    "Os Mutantes",
    "The Zombies",
    "The Byrds",
    "The Kinks",
    "The Doors",
    "The Rolling Stones",
    "The Who",
    "The Tower Recordings",
    "The Incredible String Band",
    "The Band",
    "The Lumineers",
    "The Tall Dwarfs",
    "Lee Scratch Perry",
    "Can",
    "Kraftwerk",
    "Brian Eno",
    "Faust",
    "Tangerine Dream",
    "Neu!",
    "Amon Düül II",
    "Cluster",
    "Ash Ra Tempel",
    "Harmonia",
    "Popol Vuh",
    "Gong",
    "Soft Machine",
    "The United States of America",
    "The Silver Apples",
    "Television",
    "Television Personalities",
    "The Waterboys",
    "The Pogues",
    "Julian Cope",
    "The Teardrop Explodes",
    "Bruce Haack",
    "The Shaggs",
    "The Residents",
    "Leonard Cohen",
    "Woodie Guthrie",
    "Bob Dylan",
    "Neil Young",
    "Led Zeppelin",
    "Black Sabbath",
    "My Bloody Valentine",
    "Patti Smith",
    "Guided by Voices",
    "The Magnetic Fields",
    "Amen Dunes",
    "Swan Lake",
    "Mount Eerie",
    "Deerhunter",
    "Animal Collective",
    "Atlas Sound",
    "Derek Decker",
]