POSITIVE_GENRES: list[str] = [
    "Art Pop",
    "Art Rock",
    "Baroque Pop",
    "Goth",
    "Lo-Fi",
    "Musique Concrète",
    "Indie Rock",
    "New Wave",
    "Shoegaze",
    "Post-Punk",
    "Avant-Garde Classical",
    "Impressionist Classical",
    "Minimalism",
    "Modern Composition",
    "Americana",
    "Nashville Sound",
    "Minimal House",
    "Ambient Electronic",
    "Electropop",
    "Electroacoustic",
    "Sound Art",
    "Experimental Electronic",
    "Experimental Rock",
    "Experimental Pop",
    "Experimental Hip Hop",
    "Experimental Jazz",
    "Experimental Classical",
    "Experimental Folk",
    "Experimental Country",
    "Experimental Blues",
    "Industrial",
    "Vaporwave",
    "Psychedelic Folk",
    "Nerdcore",
    "Coldwave",
    "Dark Ambient",
    "Drone Music",
    "Post-Rock",
    "Noise",
    "Free Jazz",
    "Avantgarde Metal",
    "Psychedelic Pop",
    "Psychedelic Rock",
    "Psychedelic Soul",
    "Psychedelic Electronic",
    "Psychedelic Hip Hop",
    "Psychedelic Country",
    "Psychedelic Blues",
    "Psychedelic Folk",
    "Surf Pop",
    "Spaceage Rock",
    "Space Rock",
    "Glam Rock",
    "Surf Rock",
    "Soundtrack",
    "Celtic Folk"
]