BOUNDARY_WORDS = [
    # Core boundary concepts
    "boundary",
    "between",
    "neither",
    "both",
    "category",
    "map",
    # Liminal states
    "liminal",
    "threshold",
    "edge",
    "border",
    "borderline",
    "margin",
    "fringe",
    "transition",
    "transitional",
    "intermediate",
    "in-between",
    "midway",
    # Ambiguity and uncertainty
    "ambiguous",
    "unclear",
    "vague",
    "fuzzy",
    "blurred",
    "blurry",
    "hazy",
    "indistinct",
    "indefinite",
    "nebulous",
    "murky",
    "obscure",
    # Neither/nor constructions
    "nor",
    "either",
    "or",
    "and",
    "not quite",
    "sort of",
    "kind of",
    "somewhat",
    "partially",
    "half",
    "halfway",
    "partly",
    # Category confusion
    "categorize",
    "classify",
    "define",
    "distinction",
    "separate",
    "divide",
    "differentiate",
    "discriminate",
    "demarcate",
    # Overlap and intersection
    "overlap",
    "intersect",
    "intersection",
    "cross",
    "crossing",
    "hybrid",
    "mixed",
    "merged",
    "blended",
    "fused",
    "combined",
    # Threshold experiences
    "verge",
    "brink",
    "cusp",
    "precipice",
    "periphery",
    "perimeter",
    "limit",
    "extent",
    "extreme",
    "outermost",
    "frontier",
    # Gray areas
    "grey",
    "gray",
    "spectrum",
    "gradient",
    "gradual",
    "gradation",
    "continuum",
    "range",
    "span",
    "between-ness",
    # Uncertainty markers
    "uncertain",
    "unsure",
    "doubtful",
    "questionable",
    "debatable",
    "contested",
    "disputed",
    "unresolved",
    "undecided",
    "open",
    # State changes
    "transform",
    "shift",
    "change",
    "mutation",
    "metamorphosis",
    "conversion",
    "becoming",
    "turning",
    "evolving",
    "transitioning",
    # Belonging/not belonging
    "belong",
    "fit",
    "place",
    "classify",
    "categorize",
    "label",
    "define",
    "identify",
    "name",
    "designate",
]
